/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbara.visao;

import Util.NovoHibernateUtil;
import br.com.barbara.Classes.Clientes;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Iterator;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;
import br.com.barbara.visao.Parcelamentos;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author anton
 */
public class DebitoCliente extends javax.swing.JDialog {
   private  DefaultTableModel tmResultSet = new DefaultTableModel(null, new String[]{"ID","NOME","APELIDO", "CPF", "TELEFONE","LOGRADOURO","N°","BAIRRO","CIDADE","ESTADO"});;
   java.util.List<Clientes> resultado;  
      private ListSelectionModel lsmResult;
      private DefaultTableModel tabela;
      
      
     private Integer idCliente;
     private String nome;
     private String apelido;
     private String cpf;
     private String telefone;
     private String logradouro;
     private int numero;
     private String bairro;
     private String cidade;
     private String estado;

    /**
     * Creates new form DebitoCliente
     */
    public DebitoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupCliente = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);          lsmResult = jTable1.getSelectionModel();          lsmResult.addListSelectionListener(new ListSelectionListener() {               public void valueChanged(ListSelectionEvent e) {                                        if (! e.getValueIsAdjusting()){                           jTTabelaLinhaSelecionada(jTable1);                       }                                    }          });
        jTPesquisa = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CLIENTES EM DEBITO - SCE - TEC.INOVA");

        jPanel1.setBackground(new java.awt.Color(0, 140, 35));
        jPanel1.setForeground(new java.awt.Color(0, 140, 35));

        jTable1.setModel(tmResultSet);
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("PESQUISA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(622, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTPesquisa.equals("")){
            mostraPesquisa();

        }else{
            mostraPesquisaFiltro(jTPesquisa.getText());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebitoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebitoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebitoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebitoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DebitoCliente dialog = new DebitoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


private void pesquisaSelecionadaCliente(String text) {
Session sesion = NovoHibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Criteria crit = sesion.createCriteria(Clientes.class);
        crit.add(Restrictions.like("nome",text+"%"));
        java.util.List results = crit.list();
        for (Iterator iterator = results.iterator(); iterator.hasNext();){
        Clientes Sal = (Clientes) iterator.next();  
        
        
         JMenuItem item = new JMenuItem(Sal.getIdCliente()+","+Sal.getNome());
          item.addActionListener(new ActionListener() {
           @Override
            public void actionPerformed(ActionEvent arg0){
             String mods = item.getText();
             String campos[] = mods.split(",");
          
             jTPesquisa.setText(campos[1]);
          
         
           }});
          jPopupCliente.add(item);
             }

         

}
private void mostraPesquisa() {
         tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = NovoHibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Criteria crit = sesion.createCriteria(Clientes.class);
        //crit.add(Restrictions.like("descricao",text+"%"));
        java.util.List results = crit.list();
        for (Iterator iterator = results.iterator(); iterator.hasNext();){
        Clientes Sal = (Clientes) iterator.next(); 
        tmResultSet.addRow(new Object[]{
            //`enter code here`columns
            Sal.getIdCliente(),
            Sal.getNome(),
            Sal.getApelido(),
            Sal.getCpf(),
            Sal.getTelefone(),
            Sal.getLogradouro(),
            Sal.getNumero(),
            Sal.getBairro(),
            Sal.getCidade(),
            Sal.getEstado()
            
        });
        }
       
        
 
      }
//código para linha selecionada, restante do codigo está na tabela
      private void jTTabelaLinhaSelecionada(JTable tabela) {
           if (jTable1.getSelectedRow()!= -1) {     
          String cod = (jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString();
                   this.idCliente = Integer.parseInt(cod);
                   this.nome = (jTable1.getValueAt(jTable1.getSelectedRow(),1)).toString();
          this.apelido = (jTable1.getValueAt(jTable1.getSelectedRow(),2)).toString();
          this.cpf = (jTable1.getValueAt(jTable1.getSelectedRow(),3)).toString();
          this.telefone = (jTable1.getValueAt(jTable1.getSelectedRow(),4)).toString();
          this.logradouro = (jTable1.getValueAt(jTable1.getSelectedRow(),5)).toString();
          String num = (jTable1.getValueAt(jTable1.getSelectedRow(),6)).toString();
          this.numero = Integer.parseInt(num);
          this.bairro = (jTable1.getValueAt(jTable1.getSelectedRow(),7)).toString();
          this.cidade = (jTable1.getValueAt(jTable1.getSelectedRow(),8)).toString();
          this.estado = (jTable1.getValueAt(jTable1.getSelectedRow(),9)).toString();      
          
                   jogaValor(idCliente, this.nome);
           }
      /*  if (jTable1.getSelectedRow()!= -1) {
           
          this.id = resultado.get(tabela.getSelectedRow()).getIdProduto();
          this.descricao = resultado.get(tabela.getSelectedRow()).getDescricao();
          this.unCompra = resultado.get(tabela.getSelectedRow()).getUnidadeCompra();
          this.unVenda = resultado.get(tabela.getSelectedRow()).getUnidadeVenda();
          this.fornecedor = resultado.get(tabela.getSelectedRow()).getIdFornecedor();
          this.marca = resultado.get(tabela.getSelectedRow()).getIdMarca();
          
          
          System.out.println("Conheça nossos produtos: "+this.descricao);
          
          
        }*/
        
        
     }  
//pega o valor das variaveis do inicio e joga na tela
    private void jogaValor(int id, String nome) {
       Mensalidade m = new Mensalidade(null, true);
       m.recebevalor(id, nome);
        m.setVisible(true);
    }
    //limpa os campos
    private void limpaCampos(){
       
        tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
    }

 

    private void mostraPesquisaFiltro(String text) {
 tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = NovoHibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Criteria crit = sesion.createCriteria(Clientes.class);
        crit.add(Restrictions.like("nome",text+"%"));
        java.util.List results = crit.list();
        for (Iterator iterator = results.iterator(); iterator.hasNext();){
        Clientes Sal = (Clientes) iterator.next(); 
        tmResultSet.addRow(new Object[]{
            //`enter code here`columns
            Sal.getIdCliente(),
            Sal.getNome(),
            Sal.getApelido(),
            Sal.getCpf(),
            Sal.getTelefone(),
            Sal.getLogradouro(),
            Sal.getNumero(),
            Sal.getBairro(),
            Sal.getCidade(),
            Sal.getEstado()
            
        });
        }    }

}

