/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbara.visao;

import Util.NovoHibernateUtil;
import br.com.barbara.Classes.Clientes;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author anton
 */
public class Mensalidade extends javax.swing.JDialog {
   private  DefaultTableModel tmResultSet = new DefaultTableModel(null, new String[]{"JANEIRO","FEVEREIRO","MARCO", "ABRIL", "MAIO","JUNHO","JULHO°","AGOSTO","SETEMBRO","OUTUBRO","NOVEMBRO","DEZEMBRO"});;
    java.util.List<br.com.barbara.Classes.Mensalidade> resultado;  
      private ListSelectionModel lsmResult;
      private DefaultTableModel tabela;
   private int id;
   private String nome;
   private String mes;
   private int pagamento;
   //variaveis para updadte e pagamento das mensalidades
   private int idMensalidade;
   Date dataEntrada;
    int m1;
        int m2;
        int m3;
        int m4;
        int m5;
        int m6;
        int m7;
        int m8;
        int m9;
        int m10;
        int m11;
        int m12;
   
   
    /**
     * Creates new form Mensalidade
     */
    public Mensalidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jLId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLMensalidade = new javax.swing.JLabel();
        jLValorPago = new javax.swing.JLabel();
        jLValorDevido = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCMes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 140, 35));

        jTable1.setModel(tmResultSet);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ANO:");

        jLNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNome.setForeground(new java.awt.Color(255, 255, 255));
        jLNome.setText("CLIENTE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        jLCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCliente.setForeground(new java.awt.Color(255, 255, 255));

        jLId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLId.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VALOR MENSALIDADE:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VALOR PAGO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VALOR DEVIDO:");

        jLMensalidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLMensalidade.setForeground(new java.awt.Color(255, 255, 255));
        jLMensalidade.setText("jLabel9");

        jLValorPago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLValorPago.setForeground(new java.awt.Color(255, 255, 255));
        jLValorPago.setText("jLabel10");

        jLValorDevido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLValorDevido.setForeground(new java.awt.Color(255, 255, 255));
        jLValorDevido.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MÊS");

        jCMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ...", " " }));
        jCMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMesActionPerformed(evt);
            }
        });

        jButton1.setText("QUITAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLId, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLMensalidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jLValorDevido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCMes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLNome)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLMensalidade)
                    .addComponent(jLabel12)
                    .addComponent(jCMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLValorPago)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLValorDevido))
                .addGap(244, 244, 244))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(783, 333));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMesActionPerformed
      /* 
*/
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jCMesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int controle = 0;
          funcaoSelecionaMesPagamento();

        br.com.barbara.Classes.Mensalidade mensal = new br.com.barbara.Classes.Mensalidade();
        mensal.setAno(jComboBox1.getSelectedItem().toString());
        mensal.setDataEntrada(dataEntrada);
        mensal.setIdCliente(id);
        mensal.setIdmensalidade(idMensalidade);
        mensal.setValor(Float.parseFloat(jLMensalidade.getText()));
        
        
         if(jCMes.getSelectedItem().equals("Selecione ...")){
           
       }
    if(jCMes.getSelectedItem().equals("Janeiro")){
            mensal.setM1(1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Fevereiro")){
             mensal.setM1(this.m1);
            mensal.setM2(1);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Março")){
             mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(1);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Abril")){
             mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(1);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Maio")){
              mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(1);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Junho")){
              mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(1);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Julho")){
             mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(1);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Agosto")){
              mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(1);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Setembro")){
              mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(1);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Outubro")){
             mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(1);
            mensal.setM11(this.m11);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Novembro")){
             mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(1);
            mensal.setM12(this.m12);
        }
    if(jCMes.getSelectedItem().equals("Dezembro")){
            mensal.setM1(this.m1);
            mensal.setM2(this.m2);
            mensal.setM3(this.m3);
            mensal.setM4(this.m4);
            mensal.setM5(this.m5);
            mensal.setM6(this.m6);
            mensal.setM7(this.m7);
            mensal.setM8(this.m8);
            mensal.setM9(this.m9);
            mensal.setM10(this.m10);
            mensal.setM11(this.m11);
            mensal.setM12(1);
        }     
       
        
       
        Session salvar = NovoHibernateUtil.getSessionFactory().openSession();
        salvar.beginTransaction();
        salvar.update(mensal);
        salvar.getTransaction().commit();
        JOptionPane.showMessageDialog(rootPane, "Pagamento Efetuado COM SUCESSO!");
        fecharFrame();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mensalidade dialog = new Mensalidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public void recebevalor(int id, String nome){
    this.nome = nome;
    this.id= id;
    jLCliente.setText(nome);
    jLId.setText(String.valueOf(this.id));
    mostraPesquisaFiltro(nome);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCMes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLMensalidade;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLValorDevido;
    private javax.swing.JLabel jLValorPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

 private void mostraPesquisaFiltro(String text) {
 tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = NovoHibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Criteria crit = sesion.createCriteria(br.com.barbara.Classes.Mensalidade.class);
        //crit.add(Restrictions.like("nome",text+"%"));
        java.util.List results = crit.list();
        for (Iterator iterator = results.iterator(); iterator.hasNext();){
        br.com.barbara.Classes.Mensalidade Sal = (br.com.barbara.Classes.Mensalidade) iterator.next(); 
        if(this.id == Sal.getIdCliente()){
        jComboBox1.addItem(Sal.getAno());
        jLMensalidade.setText(String.valueOf(Sal.getValor()));
        float valorAberto = 0;
        float valorPago = 0;
        String m1 = null;
        String m2 = null;
        String m3 = null;
        String m4 = null;
        String m5 = null;
        String m6 = null;
        String m7 = null;
        String m8 = null;
        String m9 = null;
        String m10 = null;
        String m11 = null;
        String m12 = null;
        this.dataEntrada = Sal.getDataEntrada();
        this.idMensalidade = Sal.getIdmensalidade();
        jCMes.removeAllItems();
        if(Sal.getM1() == 0){
            valorAberto = valorAberto+50;
            m1 = "ABERTO";
            jCMes.addItem("Janeiro");
        }
        if(Sal.getM1() == 1){
           valorPago = valorPago + 50; 
           m1 = "PAGO";
          
        }
        
        
         if(Sal.getM2() == 0){
            valorAberto = valorAberto+50;
             m2 = "ABERTO";
             jCMes.addItem("Fevereiro");
        }
        if(Sal.getM2() == 1){
           valorPago = valorPago + 50; 
            m2 = "PAGO";
            
        }
        
         if(Sal.getM3() == 0){
            valorAberto = valorAberto+50;
             m3 = "ABERTO";
             jCMes.addItem("Março");
        }
        if(Sal.getM3() == 1){
           valorPago = valorPago + 50; 
            m3 = "PAGO";
        }
        
         if(Sal.getM4() == 0){
            valorAberto = valorAberto+50;
             m4 = "ABERTO";
             jCMes.addItem("Abril");
        }
        if(Sal.getM4() == 1){
           valorPago = valorPago + 50; 
            m4 = "PAGO";
       }
        
         if(Sal.getM5() == 0){
            valorAberto = valorAberto+50;
             m5 = "ABERTO";
             jCMes.addItem("Maio");
        }
        if(Sal.getM5() == 1){
           valorPago = valorPago + 50; 
            m5 = "PAGO";
        }
         if(Sal.getM6() == 0){
            valorAberto = valorAberto+50;
             m6 = "ABERTO";
             jCMes.addItem("Junho");
             
        }
        if(Sal.getM6() == 1){
           valorPago = valorPago + 50; 
            m6 = "PAGO";
        }
         if(Sal.getM7() == 0){
            valorAberto = valorAberto+50;
             m7 = "ABERTO";
             jCMes.addItem("Julho");
        }
        if(Sal.getM7() == 1){
           valorPago = valorPago + 50;
            m7 = "PAGO";
        }
         if(Sal.getM8() == 0){
            valorAberto = valorAberto+50;
             m8 = "ABERTO";
             jCMes.addItem("Agosto");
        }
        if(Sal.getM8() == 1){
           valorPago = valorPago + 50; 
            m8 = "PAGO";
        }
         if(Sal.getM9() == 0){
            valorAberto = valorAberto+50;
             m9 = "ABERTO";
             jCMes.addItem("Setembro");
        }
        if(Sal.getM9() == 1){
           valorPago = valorPago + 50; 
            m9 = "PAGO";
        }
         if(Sal.getM10() == 0){
            valorAberto = valorAberto+50;
             m10 = "ABERTO";
             jCMes.addItem("Outubro");
        }
        if(Sal.getM10() == 1){
           valorPago = valorPago + 50; 
            m10 = "PAGO";
        }
         if(Sal.getM11() == 0){
            valorAberto = valorAberto+50;
             m11 = "ABERTO";
             jCMes.addItem("Novembro");
        }
        if(Sal.getM11() == 1){
           valorPago = valorPago + 50;
            m11 = "PAGO";
        }
         if(Sal.getM12() == 0){
            valorAberto = valorAberto+50;
             m12 = "ABERTO";
             jCMes.addItem("Dezembro");
        }
        if(Sal.getM12() == 1){
           valorPago = valorPago + 50; 
            m12 = "PAGO";
            
        }
        this.m1 = Sal.getM1();
        this.m2 = Sal.getM2();
        this.m3 = Sal.getM3();
        this.m4 = Sal.getM4();
        this.m5 = Sal.getM5();
        this.m6 = Sal.getM6();
        this.m7 = Sal.getM7();
        this.m8 = Sal.getM8();
        this.m9 = Sal.getM9();
        this.m10 = Sal.getM10();
        this.m11 = Sal.getM11();
        this.m12 = Sal.getM12();
        jLValorDevido.setText(String.valueOf(valorAberto));
        jLValorPago.setText(String.valueOf(valorPago));
        
        
        tmResultSet.addRow(new Object[]{
            //`enter code here`columns
           /* Sal.getIdCliente(),
            Sal.getAno(),
            Sal.getDataEntrada(),*/
            m1,
            m2,
            m3,
            m4,
            m5,
            m6,
            m7,
            m8,
            m9,
            m10,
            m11,
            m12
            
               
        });
        }
        }
 }
public void funcaoSelecionaMesPagamento(){
    if(jCMes.getSelectedItem().equals("Selecione ...")){
           
       }
    if(jCMes.getSelectedItem().equals("Janeiro")){
            this.m1 = 1;
            this.mes = "m1";
        }
    if(jCMes.getSelectedItem().equals("Fevereiro")){
            this.m2 = 1;
            this.mes = "m2";
        }
    if(jCMes.getSelectedItem().equals("Março")){
            this.m3 = 1;
            this.mes = "m3";
        }
    if(jCMes.getSelectedItem().equals("Abril")){
            this.m4 = 1;
            this.mes = "m4";
        }
    if(jCMes.getSelectedItem().equals("Maio")){
            this.m5 = 1;
            this.mes = "m5";
        }
    if(jCMes.getSelectedItem().equals("Junho")){
            this.m6 = 1;
            this.mes = "m6";
        }
    if(jCMes.getSelectedItem().equals("Julho")){
            this.m7 = 1;
            this.mes = "m7";
        }
    if(jCMes.getSelectedItem().equals("Agosto")){
            this.m8 = 1;
            this.mes = "m8";
        }
    if(jCMes.getSelectedItem().equals("Setembro")){
            this.m9 = 1;
            this.mes = "m9";
        }
    if(jCMes.getSelectedItem().equals("Outubro")){
            this.m10 = 1;
            this.mes = "m10";
        }
    if(jCMes.getSelectedItem().equals("Novembro")){
            this.m11 = 1;
            this.mes = "m11";
        }
    if(jCMes.getSelectedItem().equals("Dezembro")){
            this.m12 = 1;
            this.mes = "m12";
        }
    }

    private void fecharFrame() {
this.dispose();
        }
}

