package br.com.barbara.Classes;
// Generated 14/04/2019 23:32:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Financeiro generated by hbm2java
 */
public class Financeiro  implements java.io.Serializable {


     private Integer idFinanceiro;
     private String mesReferencia;
     private int idMensalidade;
     private Date dataPagamento;
     private int idCliente;
     private float valorPagamento;

    public Financeiro() {
    }

    public Financeiro(String mesReferencia, int idMensalidade, Date dataPagamento, int idCliente, float valorPagamento) {
       this.mesReferencia = mesReferencia;
       this.idMensalidade = idMensalidade;
       this.dataPagamento = dataPagamento;
       this.idCliente = idCliente;
       this.valorPagamento = valorPagamento;
    }
   
    public Integer getIdFinanceiro() {
        return this.idFinanceiro;
    }
    
    public void setIdFinanceiro(Integer idFinanceiro) {
        this.idFinanceiro = idFinanceiro;
    }
    public String getMesReferencia() {
        return this.mesReferencia;
    }
    
    public void setMesReferencia(String mesReferencia) {
        this.mesReferencia = mesReferencia;
    }
    public int getIdMensalidade() {
        return this.idMensalidade;
    }
    
    public void setIdMensalidade(int idMensalidade) {
        this.idMensalidade = idMensalidade;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public float getValorPagamento() {
        return this.valorPagamento;
    }
    
    public void setValorPagamento(float valorPagamento) {
        this.valorPagamento = valorPagamento;
    }




}


